### ISSUE TITLE
Feature request: Support Firefox Forks

### ISSUE THREAD

**Issue by MisterMonstr** [null-dev/firefox-profile-switcher-connector#8]
I think it'd be great if this supported Firefox forks. I was hoping to use this with LibreWolf on my Fedora 35 install (KDE/Wayland), kept getting "Setup incomplete!" in the add-on and found out that it only works in Firefox.

**Comment by null-dev** [comment]
The extension does have "unofficial" (because I don't test with them often) support for Firefox forks however it is undocumented and requires additional configuration.

How did you install LibreWolf? Did you use `dnf`? Or flatpak?

**Comment by MisterMonstr** [comment]
Thanks for the quick response! I installed it through LibreWolf's official Fedora repository with dnf.

**Comment by null-dev** [comment]
Alright, here's the setup instructions:

First install the `.rpm` file the setup page instructed you to install if you haven't done so already.

Then, run the following two commands to show LibreWolf where to find the executable:
```sh
mkdir -p ~/.librewolf/native-messaging-hosts
ln -s /usr/lib/mozilla/native-messaging-hosts/ax.nd.profile_switcher_ff.json ~/.librewolf/native-messaging-hosts/ax.nd.profile_switcher_ff.json
```

Now you need to configure the profile switcher to search for LibreWolf profiles instead of Firefox profiles. You can do this by running the below commands:
```sh
mkdir -p ~/.config/firefoxprofileswitcher
echo '
{
    "browser_profile_dir": "'"$HOME"'/.librewolf",
    "browser_binary": "/usr/bin/librewolf"
}
' > ~/.config/firefoxprofileswitcher/config.json
```

Everything should work after that, let me know if you have any trouble.

**Comment by MisterMonstr** [comment]
Nice! It works! Thanks for the help!
